auleblog/urls.py
#coding: utf-8

from django.urls import path, re_path
from django.contrib.sitemaps.views import sitemap
from .sitemaps import BlogSitemap
import auleblog.views

sitemaps = {'posts':BlogSitemap}

urlpatterns = [
    path('', auleblog.views.articlesViews, name='articles_list'),
    re_path(r'^find-article/$', auleblog.views.find_by_title),
    re_path(r'^news/(?P<article_id>\d+)/pdf/$', auleblog.views.articleToPdf, name='pdf'),
    re_path(r'^articles/rss/', auleblog.views.NewEntries(), name='new_entry'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^article-details/(?P<slug>[-\w\d]+),(?P<pk>\d+)/$', auleblog.views.ArticleDetailView.as_view(), name='article-details'),
    re_path('^my_form/$', auleblog.views.CommentFormView.as_view(), name='my_form_view_url'),
    re_path('category/(?P<pk>\d+)', auleblog.views.CategoryListView.as_view(), name="article-category"),
]

auleblog/models.py
#coding: utf-8

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=256)

    def __str__(self):
        return str("%s" % (self.category_name))


class Article(models.Model):
    title = models.CharField(max_length=256)
    meta_description = models.CharField(max_length=155, blank=True)
    meta_keywords = models.CharField(max_length=256, blank=True)
    url_title = models.SlugField(max_length=50)
    content = models.TextField()
    date_pub = models.DateField()
    active = models.BooleanField(verbose_name="Aktywne")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    counter = models.IntegerField(default=0)
    category_article_id = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return "{title}".format(title=self.title)

    def get_absolute_url(self):
        return "/article-details/%s%s%s/" % (self.url_title, ',', self.id)

    def absolute_title(self):
        return "%s" % self.title

    class Meta:
        ordering = ['date_pub']


class Comment(models.Model):
    add_date = models.DateTimeField(auto_now_add=True)
    comment_author = models.CharField(max_length=256)
    comment_content = models.TextField()
    post = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return str("%s: %s" % (self.comment_author, self.comment_content[:60]))

auleblog/templates/blog/article.html
{% extends "base.html" %}

{% block title %}
<title>{{ art.title }}</title>
{% endblock %}

{% block meta_description %}
<meta name="Description" content='{{ art.meta_description }}' />
{% endblock %}

{% block meta_keywords %}
<meta name="Keywords" content='{{ art.meta_keywords }}' />
{% endblock %}

{% block content %}
            <h2 class="blog-post-title">{{ art.title }}</h2>
            <p class="blog-post-meta"><strong>{{ art.date_pub }}</strong> popełniony przez <strong>{{ art.article_author }}</strong></p>
            <p>{{ art.content|safe}}</p>
            <p class="coment-text text-right"><a href="{% url 'pdf' article_id=art.id %}"><span class="glyphicon glyphicon-save-file" aria-hidden="true"></span>Wersja PDF</a></p>
			<hr>
			<nav>
            <ul class="pager">
				{% if prev %}<li><a href="{%url 'article' prev.url_title prev.id %}">Poprzedni</a></li>{% endif %}
				<li><a href="{% url 'articles_list' %}">Powrót</a></li>
				{% if next %}<li><a href="{%url 'article' next.url_title next.id %}">Nastepny</a></li>{% endif %}
            </ul>
          </nav>
		  <!-- Dodawanie komentarzy -->
		  {% if comment %}
		  <p>Komentarze:</p>
		  <div class="media">
		  <table class="table table-striped">
		  {% for comment in comment %}
				<tr>
				<td>
				<div class="media_body">
				<h6 class="media-heading"><p class="coment-title"><strong>{{ comment.comment_author }}</strong></h6>
				<p class="coment-text">{{ comment.comment_content }}<br /><p>
				<p class="sub-text">{{ comment.comment_add_data }}</p>
				</div>
				</td>
				</tr>
			{% endfor %}
		  </table>
		  </div>
		  {% endif %}
		  <p>Dodaj komentarz:</p>
		  <form method="post">
			  {% csrf_token %}
		  <div class="form-group">
			{{form.comment_author}}
			</div>
			<div class="form-group">
			{{form.comment_content}}
			</div>
			<div class="form-group">
			{{form.post}}
			</div>
			<button type="submit" class="btn btn-default btn-sm">Dodaj</button>
		</form>
{% endblock %}

auleblog/templates/blog/article_detail.html
{% extends "base.html" %}

{% block title %}
<title>{{ art.title }}</title>
{% endblock %}

{% block meta_description %}
<meta name="Description" content='{{ art.meta_description }}' />
{% endblock %}

{% block meta_keywords %}
<meta name="Keywords" content='{{ art.meta_keywords }}' />
{% endblock %}

{% block content %}
            <h2 class="blog-post-title">{{ art.title }}</h2>
            <p class="blog-post-meta"><strong>{{ art.date_pub }}</strong> popełniony przez <strong>{{ art.article_author }}</strong></p>
            <p>{{ art.content|safe}}</p>
			<p class="coment-text text-right"><a href="{% url 'pdf' article_id=art.id %}"><span class="glyphicon glyphicon-save-file" aria-hidden="true"></span>Wersja PDF</a></p>
			<hr>
			<nav>
            <ul class="pager">
				{% if prev %}<li><a href="{%url 'article-details' prev.url_title prev.id %}">Poprzedni</a></li>{% endif %}
				<li><a href="{% url 'articles_list' %}">Powrót</a></li>
				{% if next %}<li><a href="{%url 'article-details' next.url_title next.id %}">Nastepny</a></li>{% endif %}
            </ul>
          </nav>
		  <!-- Dodawanie komentarzy -->
		  {% if comment %}
		  <p>Komentarze:</p>
		  <div class="media">
		  <table class="table table-striped">
		  {% for comment in comment %}
				<tr>
				<td>
				<div class="media_body">
				<h6 class="media-heading"><p class="coment-title"><strong>{{ comment.comment_author }}</strong></h6>
				<p class="coment-text">{{ comment.comment_content }}<br /><p>
				<p class="sub-text">{{ comment.comment_add_data }}</p>
				</div>
				</td>
				</tr>
			{% endfor %}
		  </table>
		  </div>
		  {% endif %}
		  <p>Dodaj komentarz:</p>
		  <form method="post" action="{% url 'my_form_view_url' %}">
			  {% csrf_token %}
		  <div class="form-group" >
			{{form.comment_author}}
			</div>
			<div class="form-group">
			{{form.comment_content}}
			</div>
			<div class="form-group">
			{{form.post}}
			</div>
			<button type="submit" class="btn btn-default btn-sm">Dodaj</button>
		</form>
{% endblock %}

auleblog/templates/blog/articles.html
{% extends "base.html" %}

{% block title %}
<title>Aule Blog</title>
{% endblock %}

{% block meta_description %}
<meta name="Description" content="Blog programisty amatora który zamieszcza tutaj posty związane z etapami tworzenia
tego bloga w Django jak również innych aplikacji stworzonych przez niego w Django." />
{% endblock %}

{% block meta_keywords %}
<meta name="Keywords" content="Django, Blog, Tworzenie aplikacji, Python, Aplikacje w Django" />
{% endblock %}

{% block content %}
			{% for articles in article_all_pagination %}
            <h2 class="blog-post-title"><a href="{% url 'article-details' slug=articles.url_title pk=articles.id %}">{{ articles.title }}</a></h2>
            <p class="blog-post-meta"><strong>{{ articles.date_pub }}</strong> popełniony przez <strong>{{ articles.author }}</strong></p>
            <p>{{ articles.content|safe|escape|truncatechars:150 }}</p>
            <div class="row">
                <div class="col-sm-6">
                    <p class="coment-text text-left">Liczba odwiedzin: {{ articles.counter }}</p>
                </div>
                <div class="col-sm-6">
                    <p class="coment-text text-right">Komentarze: {{ articles.comment_set.count }}</p>
                </div>
            </div>
			<hr>
			{% endfor %}

			<div class="pagination">
   <span class="step-links">
        {% if page_filter.has_previous %}
            <a href="?page={{ article_all_pagination.previous_page_number }}">poprzednia</a>
        {% endif %}

        <span class="current">
            Strona {{ article_all_pagination.number }} z {{ article_all_pagination.paginator.num_pages }}
        </span>

        {% if page_filter.has_next %}
            <a href="?page={{ article_all_pagination.next_page_number }}">następna</a>
        {% endif %}
    </span>
</div>
{% endblock %}

auleblog/templates/blog/category.html
{% extends "base.html" %}

{% block title %}
<title>Aule Blog {{ all_categories.category_name }}</title>
{% endblock %}

{% block meta_description %}
<meta name="Description" content='Wpisy powiązane z kategorią {{ all_categories.category_name }}' />
{% endblock %}

{% block meta_keywords %}
<meta name="Keywords" content='{{ all_categories.category_name }}' />
{% endblock %}


{% block content %}
			{% for wszystkie in choose_category %}
            <h2 class="blog-post-title"><a href="{% url 'article-details' slug=wszystkie.url_title pk=wszystkie.id %}">{{ wszystkie.title }}</a></h2>
            <p class="blog-post-meta"><strong>{{ wszystkie.date_pub }}</strong> popełniony przez <strong>{{ wszystkie.author }}</strong></p>
            <p>{{ wszystkie.content|safe|escape|truncatechars:150 }}</p>
            <div class="row">
                <div class="col-sm-6">
                    <p class="coment-text text-left">Liczba odwiedzin: {{ wszystkie.counter }}</p>
                </div>
                <div class="col-sm-6">
                    <p class="coment-text text-right">Komentarze: {{ wszystkie.comment_set.count }}</p>
                </div>
            </div>
			<hr>
			{% endfor %}
{% endblock %}

auleblog/templates/blog/categoryviewhtml.html
{% extends "base.html" %}

{% block title %}
<title>Aule Blog {{ all_categories.category_name }}</title>
{% endblock %}

{% block meta_description %}
<meta name="Description" content='Wpisy powiązane z kategorią {{ all_categories.category_name }}' />
{% endblock %}

{% block meta_keywords %}
<meta name="Keywords" content='{{ all_categories.category_name }}' />
{% endblock %}


{% block content %}
			{% for wszystkie in choose_category %}
            <h2 class="blog-post-title"><a href="{% url 'article' slug=wszystkie.url_title title=wszystkie.id %}">{{ wszystkie.title }}</a></h2>
            <p class="blog-post-meta"><strong>{{ wszystkie.date_pub }}</strong> popełniony przez <strong>{{ wszystkie.article_author }}</strong></p>
            <p>{{ wszystkie.content|safe|escape|truncatechars:150 }}</p>
            <div class="row">
                <div class="col-sm-6">
                    <p class="coment-text text-left">Liczba odwiedzin: {{ wszystkie.counter }}</p>
                </div>
                <div class="col-sm-6">
                    <p class="coment-text text-right">Komentarze: {{ wszystkie.comment_set.count }}</p>
                </div>
            </div>
			<hr>
			{% endfor %}
{% endblock %}

auleblog/templates/blog/comment_form.html
{% extends "base.html" %}

{% block title %}
<title>{{ art.title }}</title>
{% endblock %}

{% block meta_description %}
<meta name="Description" content='{{ art.meta_description }}' />
{% endblock %}

{% block meta_keywords %}
<meta name="Keywords" content='{{ art.meta_keywords }}' />
{% endblock %}

{% block content %}
            <h2 class="blog-post-title">{{ art.title }}</h2>
            <p class="blog-post-meta"><strong>{{ art.date_pub }}</strong> popełniony przez <strong>{{ art.article_author }}</strong></p>
            <p>{{ art.content|safe}}</p>

			<hr>
			<nav>
            <ul class="pager">
				{% if prev %}<li><a href="{%url 'article' prev.url_title prev.id %}">Poprzedni</a></li>{% endif %}
				<li><a href="{% url 'articles_list' %}">Powrót</a></li>
				{% if next %}<li><a href="{%url 'article' next.url_title next.id %}">Nastepny</a></li>{% endif %}
            </ul>
          </nav>
		  <!-- Dodawanie komentarzy -->
		  {% if comment %}
		  <p>Komentarze:</p>
		  <div class="media">
		  <table class="table table-striped">
		  {% for comment in comment %}
				<tr>
				<td>
				<div class="media_body">
				<h6 class="media-heading"><p class="coment-title"><strong>{{ comment.comment_author }}</strong></h6>
				<p class="coment-text">{{ comment.comment_content }}<br /><p>
				<p class="sub-text">{{ comment.comment_add_data }}</p>
				</div>
				</td>
				</tr>
			{% endfor %}
		  </table>
		  </div>
		  {% endif %}
		  <p>Dodaj komentarz:</p>
		  <form method="post" action="">
			  {{form.post}}
			  {% csrf_token %}
		  <div class="form-group">
			{{form.comment_author}}
			</div>
			<div class="form-group">
			{{form.comment_content}}
			</div>
			<div class="form-group">
			{{form.post}}
			</div>
			<button type="submit" class="btn btn-default btn-sm">Dodaj</button>
		</form>
{% endblock %}